spring.application.name=hive-project

# Web 服务器运行端口
server.port=8080

# Hive JDBC 驱动
spring.datasource.driver-class-name=org.apache.hive.jdbc.HiveDriver

# HiveServer2 的连接地址。
# 【注意】请把 <你的Hadoop虚拟机IP> 替换成你实际的 IP 地址，例如 192.168.1.100
spring.datasource.url=jdbc:hive2://192.168.157.130:10000/hive_project_db

# 你的 Hive 登录用户名 (通常是启动 Hadoop 的 Linux 用户名，比如 root 或 hadoop)
spring.datasource.username=root
# 密码通常为空，如果有请填上
spring.datasource.password=