spring.application.name=hive-project

# Web server port
server.port=8080

# Hive JDBC driver class
spring.datasource.driver-class-name=org.apache.hive.jdbc.HiveDriver

# HiveServer2 connection URL
spring.datasource.url=jdbc:hive2://192.168.157.130:10000/hive_project_db

# Hive login username (usually your Linux user like root or hadoop)
spring.datasource.username=root
# Hive login password (leave empty if no password is set for Hive)
spring.datasource.password=